todo/main/urls.py
from django.urls import path
from main.views import edit_view, delete_view, MainView, CreateView

app_name = 'main'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('create/', CreateView.as_view(), name='create'),
    path('delete/', delete_view, name='delete'),
    path('edit/<int:pk>', edit_view, name='edit'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('item/', include('todo_item.urls')),
    path('registration/', include('registration.urls')),
]

todo/todo_item/urls.py
from django.urls import path
from todo_item.views import (
    item_view,
    create_view,
    edit_item_view,
    delete_item_view,
    is_done_item_view,
    ItemView,
    CreateItemView,
)

app_name = 'item'

urlpatterns = [
    path('<int:pk>', ItemView.as_view(), name='item'),
    path('create/<int:pk>', CreateItemView.as_view(), name='create'),
    path('delete/', delete_item_view, name='delete'),
    path('edit/<int:pk>', edit_item_view, name='edit'),
    path('is_done/', is_done_item_view, name='is_done'),
]

todo/todo_item/models.py
from django.db import models


class ListItem(models.Model):
    """
    Модель элемента списка
    """
    name = models.CharField(max_length=128, verbose_name='Название списка')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True, blank=True)
    list_model = models.ForeignKey('main.ListModel', on_delete=models.CASCADE)
    is_done = models.BooleanField(default=False)
    expare_date = models.DateTimeField(null=True)

    def __str__(self):
        return f'@id={self.id}@name={self.name}@list={self.list_model.name}'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save()

        items = ListItem.objects.filter(list_model=self.list_model)

        if all([item.is_done for item in items]):
            self.list_model.is_done = True
            self.list_model.save()
        else:
            self.list_model.is_done = False
            self.list_model.save()

    class Meta:
        verbose_name = 'Элемент списка'
        verbose_name_plural = 'Элементы списка'
        unique_together = ('name', 'list_model')

todo/todo_item/forms.py
from django import forms
from todo_item.models import ListItem
from django.core.exceptions import NON_FIELD_ERRORS


class ItemForm(forms.ModelForm):

    expare_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )

    class Meta:
        model = ListItem
        fields = ('name', 'list_model', 'expare_date')
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Такое дело уже существует",
            }
        }

todo/todo_item/views.py
from django.shortcuts import render, reverse, redirect
from todo_item.models import ListItem
from main.models import ListModel
from todo_item.forms import ItemForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from copy import copy
import json


class ItemView(LoginRequiredMixin, generic.ListView):
    login_url = reverse_lazy('registration:login')
    model = ListItem
    template_name = 'list.html'
    paginate_by = 6
    ordering = ['created', 'name']
    context_object_name = 'lists'

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        queryset = super().get_queryset()
        return queryset.filter(list_model_id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        list_ = ListModel.objects.select_related('user').get(id=pk)
        context['user_name'] = list_.user.username
        context['list_name'] = list_.name
        context['pk'] = pk
        return context


@login_required(login_url=reverse_lazy('registration:login'))
def item_view(request, pk):
    list_ = ListModel.objects.select_related('user').get(id=pk)
    list_items = ListItem.objects.filter(list_model=list_)

    context = {
        'lists': list_items,
        'user_name': list_.user.username,
        'list_name': list_.name,
        'pk': pk,
    }
    return render(request, 'list.html', context)


class CreateItemView(LoginRequiredMixin, generic.CreateView):
    model = ListItem
    template_name = 'new_item.html'
    form_class = ItemForm
    login_url = reverse_lazy('registration:login')

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse('item:item', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['pk'] = pk
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        query_dict = kwargs.get('data')
        pk = self.kwargs.get('pk')

        if query_dict:
            query_dict = copy(query_dict)
            query_dict['list_model'] = pk
            kwargs['data'] = query_dict

        return kwargs


@login_required(login_url=reverse_lazy('registration:login'))
def create_view(request, pk):
    form = ItemForm()

    if request.method == 'POST':
        form = ItemForm(
            data={
                'name': request.POST['name'],
                'expare_date': request.POST['expare_date'],
                'list_model': pk
            }
        )
        if form.is_valid():
            success_url = reverse('item:item', kwargs={'pk': pk})
            form.save()
            return redirect(success_url)

    context = {
        'form': form,
        'pk': pk
    }
    return render(request, 'new_item.html', context)


@login_required(login_url=reverse_lazy('registration:login'))
def edit_item_view(request, pk):
    item = ListItem.objects.get(id=pk)

    if request.method == 'POST':
        form = ItemForm(
            data={
                'name': request.POST['name'],
                'expare_date': request.POST['expare_date'],
                'list_model': item.list_model
            },
            instance=item
        )

        if form.is_valid():
            success_url = reverse('item:item', kwargs={'pk': item.list_model_id})
            form.save()
            return redirect(success_url)
    else:
        form = ItemForm(instance=item)

    context = {
        'form': form,
        'pk': pk,
        'list_model_id': item.list_model_id
    }
    return render(request, 'edit_item.html', context)


@login_required(login_url=reverse_lazy('registration:login'))
def delete_item_view(request):
    body = json.loads(request.body.decode())
    id_ = int(body.get('id', 0))

    item = ListItem.objects.filter(
        id=id_,
        list_model__user=request.user
    ).first()

    if item:
        item.delete()
        return HttpResponse(status=201)
    return HttpResponse(status=404)


@login_required(login_url=reverse_lazy('registration:login'))
def is_done_item_view(request):
    body = json.loads(request.body.decode())
    id_ = int(body.get('id', 0))

    if id_:

        item = ListItem.objects.filter(id=id_).first()

        if item:
            item.is_done = not item.is_done
            item.save()
            return HttpResponse(status=201)

    return HttpResponse(status=404)

todo/todo_item/templates/edit_item.html
{% extends 'create_master.html' %}

{% block header %}
    <div class="auth__column_right_form__header">
       Редактирование элементов списка
    </div>
{% endblock %}

{% block form %}
    <form class="auth_form_class" action="{% url 'item:edit' pk %}" id="auth_form" method="POST">
    {% csrf_token %}
    {{ form.name }}
    {{ form.expare_date }}

    {% if form.errors %}
      {{ form.non_field_errors }}
    {% endif %}

    </form>
{% endblock %}

{% block cancel_form %}
    <a href="{% url 'item:item' list_model_id %}">
        <div class="auth__button_submit" id="login-cancel-btn" ><span>&#9587</span></div>
    </a>
{% endblock %}

todo/todo_item/templates/list.html
{% extends 'master.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block name_list %}

    <div class="table-data_table-header-item-1">
        <a href="{% url 'main:main' %}" style="color: #48555F">ᐊ</a>
        <span>{{ list_name }}</span>
    </div>
{% endblock %}
{% block create %}
    <a class="add_new_list" href="{% url 'item:create' pk=pk %}">
        <div class="header__button-create-bundle">+</div>
    </a>
{% endblock %}
 {% block body %}
    {% for list in lists %}
        <div class="table-data__table-row">
        {% if list.is_done %}
            <div id="{{ list.id }}" class="table-row_table_cell-1 is_done_text"> {{ list.name }}</div>
        {% else %}
            <div id="{{ list.id }}" class="table-row_table_cell-1"> {{ list.name }}</div>
        {% endif %}
        <div class="buttons">
            <div class="table-data-two_table-icon">
                <a href="{% url 'item:edit' pk=list.id %}">
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                              d="M20 18V11H18V18H2V2H9V0H2C0.89543 0 0 0.89543 0 2V18C0 19.1046 0.89543 20 2 20H18C19.1046 20 20 19.1046 20 18ZM17.1781 0.723423C16.7197 0.26142 16.0921 0 15.4374 0C14.7834 0 14.1564 0.26083 13.6954 0.724628L5.3265 9.09342C4.57867 9.75233 4.08844 10.7328 4.00325 11.7873L4 15.0023V16.0023H8.1346C9.2689 15.9245 10.259 15.4295 10.9575 14.6238L19.279 6.30584C19.7407 5.84416 20.0001 5.21799 20.0001 4.56508C20.0001 3.91217 19.7407 3.286 19.279 2.82432L17.1781 0.723423ZM8.06398 14.0048C8.59821 13.967 9.09549 13.7184 9.49479 13.2616L15.5567 7.19972L12.8024 4.44527L6.6961 10.5496C6.29095 10.9079 6.04031 11.4092 6 11.8678V14.0029L8.06398 14.0048ZM14.2169 3.03128L16.9709 5.78551L17.8648 4.89162C17.9514 4.80502 18.0001 4.68756 18.0001 4.56508C18.0001 4.4426 17.9514 4.32514 17.8648 4.23854L15.7611 2.13486C15.6755 2.04855 15.5589 2 15.4374 2C15.3158 2 15.1992 2.04855 15.1136 2.13486L14.2169 3.03128Z"
                              fill="#FF4646"/>
                    </svg>
                </a>
            </div>
            <div class="calendarik">
                {% if list.expare_date %}
                    {{ list.expare_date | date:"SHORT_DATE_FORMAT" }}
                {% else %}
                    <a href='#'>
                        <img src="/static/images/calendar.png" alt="calendar" width="26px" height="24px">
                    </a>
                {% endif %}
            </div>
            <div class="table-row_table_icon">
                <a id="{{ list.id }}" class="delete_button" href="#">
                    <svg width="20" height="22" viewBox="0 0 20 22" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                              d="M6.99987 0H12.9999C14.1044 0 14.9999 0.89543 14.9999 2V3H18C19.1046 3 20 3.89543 20 5V7C20 8.10457 19.1046 9 18 9H17.9196L16.9997 20C16.9997 21.1046 16.1043 22 14.9997 22H4.99974C3.89517 22 2.99974 21.1046 3.00319 20.0831L2.07961 9H2C0.895431 9 0 8.10457 0 7V5C0 3.89543 0.895431 3 2 3H4.99987V2C4.99987 0.89543 5.8953 0 6.99987 0ZM4.99987 5V4.99999H1.99987V6.99999H17.9999V4.99999H14.9999V5H4.99987ZM4.99954 20L4.08603 9H15.9127L15.003 19.917L14.9995 20H4.99954ZM13.0001 1.99999V2.99999H7.00013V1.99999H13.0001Z"
                              fill="#BBC1C7"/>
                    </svg>
                </a>
             </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

{% block empty %}
    {% for _ in lists|get_count %}
        <div class="table-data__table-row">
            <div class="table-row_table_cell-1"></div>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <div class="table-data__table-row">
            <div class="paginator_class">
                <ul class="pagination-wrapper_button">
                    {% for page in paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li><a class="active" href="{% url 'item:item' pk %}?page={{ page }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="{% url 'item:item' pk %}?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
<script>
const rows = document.querySelectorAll('.table-row_table_cell-1');

const successUrl = '{% url 'item:item' pk %}';
const isDoneUrl = '{% url "item:is_done" %}';
const delUrl = '{% url "item:delete" %}';

rows.forEach(
    row => {
        if (row.innerText) {
            row.addEventListener('click', isDoneRequest);
        }
    }
);



function isDoneRequest (event) {
    console.log('click');
    const id = event.currentTarget.id;

    return fetch(isDoneUrl, {
        method: 'POST',
        headers: new Headers({'X-CSRFToken': csrftoken}),
        redirect: 'follow',
        body: JSON.stringify({id: id})
    }).then(
        respone => {
            if (respone.status === 201) {
                if (event.target.classList.contains('is_done_text')) {
                    event.target.classList.remove('is_done_text');
                } else {
                    event.target.classList.add('is_done_text');
                }
            } else {
                alert('Сервер не доступен');
            }
        }
    )
}

</script>


{% endblock %}

todo/todo_item/templates/new_item.html
{% extends 'create_master.html' %}

{% block header %}
    <div class="auth__column_right_form__header">
       Новый элемент списка
    </div>
{% endblock %}

{% block form %}
    <form class="auth_form_class" action="{% url 'item:create' pk %}" id="auth_form" method="POST">
      {% csrf_token %}
      {{ form.name }}
      {{ form.expare_date }}
    </form>
{% endblock %}

{% block cancel_form %}
    <a href="{% url 'item:item' pk %}">
        <div class="auth__button_submit" id="login-cancel-btn" ><span>&#9587</span></div>
    </a>
{% endblock %}